<li>
                                                <a title="[field:typename/]" href="[field:typeurl/]">
                                                    <i class="fa fa-joomla"></i>
                                                    <h3>[field:typename/]</h3>
                                                    <p>
                                                        基于 iOS / Android 应用开发<br>
                                                        掌控智能终端时代
                                                    </p>
                                                </a>
                                            </li>