<li>
                                                <a title="[field:typename/]" href="[field:typeurl/]">
                                                    <i class="fa fa-shield"></i>
                                                    <h3>[field:typename/]</h3>
                                                    <p>
                                                        插画、网页UI设计<br>
                                                        多种风格掌控自如
                                                    </p>
                                                </a>
                                            </li>