<?php
$z[0]=Array("field","",11,37);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,77);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",87,116);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",138,167);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n          <li class=\"nav2\"><a href=\"[field:typelink/]\" data-alert=\"全部\">[field:typename/]</a></li>\r\n          ",197,366);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="true";

?>