<li class="news_img"> <font><b>[field:pubdate function="MyDate('d',@me)"/]</b><u>[field:pubdate function="MyDate('m',@me)"/]月</u></font> <a href="[field:arcurl/]" title="[field:title/]" target='_self'> <img src="[field:litpic/]" 
title="[field:title/]" alt="[field:title/]"
data-original="[field:litpic/]" > </a> <span> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>
          <h3>[field:title/]</h3>
          </a> <em> <u>阅读</u> <i class="fa fa-eye"></i> [field:click/]
          &nbsp;·&nbsp; <u>发布日期</u> <i class="fa fa-clock-o"></i> [field:pubdate function="MyDate('Y-m-d',@me)"/]
          &nbsp;·&nbsp; <i class="fa fa-smile-o"></i> [field:scores/] </em>
          <p>[field:infos/]...</p>
          </span> </li>