<li class="case-bin">
                                                <a href="[field:arcurl/]" title="[field:title/]" style="display:block">
                                                    <font> <b></b> <img data-src="[field:litpic/]" class="swiper-lazy" title="[field:title/]" height="175" alt="[field:title/]"> </font> <span>
                                                        <h3>[field:title/]</h3>
                                                        <p>[field:infos/]...</p>
                                                    </span>
                                                </a>
                                            </li>