<li class="widget ">
              <div class="cover overlay overlay-hover"> <img class="cover-image overlay-scale" src="[field:litpic/]" alt=" [field:title/]" height="200px" style='height:200px;'/>
                <div class="overlay-panel overlay-fade overlay-background overlay-background-fixed text-center vertical-align">
                  <div class="vertical-align-middle">
                    <button type="button" class="btn btn-outline btn-inverse met-img-showbtn">
                    <a href="[field:arcurl/]">浏览</a>
                    </button>
                  </div>
                </div>
              </div>
              <div class="cover-title">
                <h3>[field:title/]</h3>
                <p> [field:infos/]... </p>
              </div>
            </li>