<?php
$z[0]=Array("global","",96,122);
$z[0][4]=array();
$z[0][4]['name']="cfg_company";
$z[1]=Array("global","",171,197);
$z[1][4]=array();
$z[1][4]['name']="cfg_company";
$z[2]=Array("global","",204,230);
$z[2][4]=array();
$z[2][4]['name']="cfg_company";
$z[3]=Array("field","(@me==\"\")? @me=\" class='nav1 active' \":@me=\"\";",499,595);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channelartlist","\r\n      <li class=\"{dede:field.currentstyle/}\"> <a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\" data-alert=\"全部\">{dede:field name='typename'/}</a>\r\n        <ul>\r\n          {dede:channel type='son' noself='true'}\r\n          <li class=\"nav2\"><a href=\"[field:typelink/]\" data-alert=\"全部\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",658,1157);
$z[4][4]=array();
$z[4][4]['row']="6";
$z[4][4]['typeid']="top";
$z[4][4]['currentstyle']="nav1 active";
$z[5]=Array("global","",1345,1367);
$z[5][4]=array();
$z[5][4]['name']="cfg_qqa";

?>