<?php
$z[0]=Array("field","",43,62);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",63,89);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",130,159);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",199,257);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1251,1286);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" class=\"\">[field:typename/]</a></li>\r\n          ",1626,1923);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['row']="6";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' title='~typename~' class='active'>~typename~</a></li>";
$z[6]=Array("global","",2031,2056);
$z[6][4]=array();
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("list","\r\n        <li class=\"case-bin pro\" style=\"width:320px;\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <font> <b></b> <img src=\"[field:litpic/]\" \r\ntitle=\"[field:title/]\" alt=\"[field:title/]\"\r\ndata-original=\"[field:litpic/]\"> </font> <span>\r\n          <h3>[field:title/]</h3>\r\n          <p>[field:infos/]...</p>\r\n          </span> </a> </li>\r\n        ",2430,2836);
$z[7][4]=array();
$z[7][4]['pagesize']="10";
$z[7][4]['infolen']="120";
$z[8]=Array("pagelist","",3002,3068);
$z[8][4]=array();
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("global","",3340,3366);
$z[9][4]=array();
$z[9][4]['name']="cfg_powerby";

?>