<?php
$z[0]=Array("field","",43,62);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",63,89);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",130,159);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",199,257);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1251,1286);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\" class=\"\">[field:typename/]</a></li>\r\n          ",1620,1917);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['row']="6";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' title='~typename~' class='active'>~typename~</a></li>";
$z[6]=Array("global","",2025,2050);
$z[6][4]=array();
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("list","\r\n            <li class=\"widget \">\r\n              <div class=\"cover overlay overlay-hover\"> <img class=\"cover-image overlay-scale\" src=\"[field:litpic/]\" alt=\" [field:title/]\" height=\"200px\" style='height:200px;'/>\r\n                <div class=\"overlay-panel overlay-fade overlay-background overlay-background-fixed text-center vertical-align\">\r\n                  <div class=\"vertical-align-middle\">\r\n                    <button type=\"button\" class=\"btn btn-outline btn-inverse met-img-showbtn\">\r\n                    <a href=\"[field:arcurl/]\">浏览</a>\r\n                    </button>\r\n                  </div>\r\n                </div>\r\n              </div>\r\n              <div class=\"cover-title\">\r\n                <h3>[field:title/]</h3>\r\n                <p> [field:infos/]... </p>\r\n              </div>\r\n            </li>\r\n            ",2594,3481);
$z[7][4]=array();
$z[7][4]['pagesize']="12";
$z[7][4]['infolen']="120";
$z[8]=Array("pagelist","",3618,3684);
$z[8][4]=array();
$z[8][4]['listsize']="5";
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[9]=Array("global","",4002,4028);
$z[9][4]=array();
$z[9][4]['name']="cfg_powerby";

?>